spring:
  application:
    name: home-api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 12000
  threadpool:
    default:
      coreSize: 10
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
