spring:
  application:
    name: product-api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 12000
  threadpool:
    default:
      coreSize: 10
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true

feign:
  hystrix:
    enabled: true

test.value: HARD

management.endpoints.web.exposure.include: '*'
