server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/mingooddev/Desktop/Spring-Cloud-Config-MSA-Example/config
          search-paths: 'hardy/*, hardy/{application}/*'
          clone-on-start: true
