server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/groot/config-msa-example/config
          search-paths: 'hardy/*, hardy/{application}/*'
          clone-on-start: true
